apiVersion: v1
appVersion: "1.0.1"
description: A Helm chart for Citrix ADC as Ingress Gateway installation in Istio Service Mesh on Kubernetes platform
name: citrix-adc-istio-ingress-gateway
version: 1.0.1
icon: https://raw.githubusercontent.com/citrix/citrix-k8s-ingress-controller/gh-pages/icon.png
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-istio-adaptor
maintainers:
- name: Dhiraj Gedam
  email: dhiraj.gedam@citrix.com
- name: Subash Dangol
  email: subash.dangol@citrix.com 
