# Default values for citrix-adc-istio-ingress-gateway
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

citrixCPX: false 

metricExporter:
    required: true
    image: quay.io/citrix/citrix-adc-metrics-exporter
    version: 1.3
    port: 8888
    secure: "YES"
    logLevel: ERROR
    imagePullPolicy: IfNotPresent

istioAdaptor:
    image: quay.io/citrix/citrix-istio-adaptor
    tag: 1.0.1
    imagePullPolicy: IfNotPresent
    netscalerUrl: null 
    proxyType: router
    secureConnect: true
    vserverIP:
    netProfile:
    ADMIP: 

istioPilot:
    name: istio-pilot
    namespace: istio-system
    secureGrpcPort: 15011
    insecureGrpcPort: 15010
    SAN: spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account

ingressGateway:
    image: quay.io/citrix/citrix-k8s-cpx-ingress
    tag: 13.0-41.28
    imagePullPolicy: IfNotPresent
    EULA: NO
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    httpNodePort: 30180
    httpsNodePort: 31443
    lightWeightCPX: YES
    secretVolumes:
    licenseServerIP:
    licenseServerPort: 27000 
    label: citrix-ingressgateway
    tcpPort:

nslogin:
   username:
   password:
