---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: bookinfo-policy
  namespace: {{ .Release.Namespace }}
spec:
  targets:
  - name: reviews
  - name: productpage
  - name: ratings
  - name: details
{{- if eq .Values.mtlsEnabled true }}
  peers:
  - mtls: {}
{{- end }}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: productpage-dr
spec:
  host: "productpage"
  trafficPolicy:
    tls:
{{- if eq .Values.mtlsEnabled true }}
      mode: ISTIO_MUTUAL
{{- else }} 
      mode: DISABLE
{{- end }}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: ratings-dr
spec:
  host: "ratings"
  trafficPolicy:
    tls:
{{- if eq .Values.mtlsEnabled true }}
      mode: ISTIO_MUTUAL
{{- else }} 
      mode: DISABLE
{{- end }}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: details-dr
spec:
  host: "details"
  trafficPolicy:
    tls:
{{- if eq .Values.mtlsEnabled true }}
      mode: ISTIO_MUTUAL
{{- else }} 
      mode: DISABLE
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-dr
spec:
  host: "reviews"
  trafficPolicy:
    tls:
{{- if eq .Values.mtlsEnabled true }}
      mode: ISTIO_MUTUAL
{{- else }} 
      mode: DISABLE
{{- end }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
